name: Setup Poetry Env

on:
  workflow_call:

jobs:

  ru2-job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Tell me what is in it
        run: |
          ls -la
      - name: give python version
        run: |
          python --version
      - name: Install poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Scream
        run: |
          echo "Poetry is installed"